name: Build action
on: [pull_request]

jobs:
  Build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Node.JS
      uses: actions/setup-node@master
      with:
        node-version: 16.x

    - name: npm install
      run: npm install

    - name: Build
      run: npm run build
